### ISSUE TITLE
SyntaxError: Unexpected token function

### ISSUE THREAD

**Issue by cheemingli** [gregolsky/whales-names#2]
With the latest `0.1.4` version I get a "SyntaxError: Unexpected token function" error message when running `whales-names`. I don't get this error with version `0.1.3`.

Detailed information about the error:
```
C:\Users\user01\AppData\Roaming\nvm\v6.17.1\node_modules\whales-names\src\index.js:10
(async function main() {
       ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\cheem\AppData\Roaming\nvm\v6.17.1\node_modules\whales-names\bin\whales-names:2:1)
```

**Comment by gregolsky** [comment]
Version 0.1.4 does not support Node.js 6 : https://github.com/gregolsky/whales-names/blob/master/package.json#L36

Node 6 reaches end-of-life on April 30th.
See https://github.com/nodejs/Release#release-schedule

For node 6, please keep using 0.1.3.
